import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });
console.log(inter);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} bg-slate-50`}>
        <Navbar />
        <div className=" flex justify-center">
          <div className=" w-4/5 pt-5 min-h-screen ">{children}</div>
        </div>
        <footer className="bg-zinc-800 shadow-inner shadow-slate-600 min-h-52"></footer>
      </body>
    </html>
  );
}
